interface InputEvent extends UIEvent {
  readonly data: string | null;
  readonly dataTransfer: DataTransfer;
  readonly inputType:
  | "insertText"
  | "insertReplacementText"
  | "insertLineBreak"
  | "insertParagraph"
  | "insertOrderedList"
  | "insertUnorderedList"
  | "insertHorizontalRule"
  | "insertFromYank"
  | "insertFromDrop"
  | "insertFromPaste"
  | "insertFromPasteAsQuotation"
  | "insertTranspose"
  | "insertCompositionText"
  | "insertLink"
  | "deleteWordBackward"
  | "deleteWordForward"
  | "deleteSoftLineBackward"
  | "deleteSoftLineForward"
  | "deleteEntireSoftLine"
  | "deleteHardLineBackward"
  | "deleteHardLineForward"
  | "deleteByDrag"
  | "deleteByCut"
  | "deleteContent"
  | "deleteContentBackward"
  | "deleteContentForward"
  | "historyUndo"
  | "historyRedo"
  | "formatBold"
  | "formatItalic"
  | "formatUnderline"
  | "formatStrikeThrough"
  | "formatSuperscript"
  | "formatSubscript"
  | "formatJustifyFull"
  | "formatJustifyCenter"
  | "formatJustifyRight"
  | "formatJustifyLeft"
  | "formatIndent"
  | "formatOutdent"
  | "formatRemove"
  | "formatSetBlockTextDirection"
  | "formatSetInlineTextDirection"
  | "formatBackColor"
  | "formatFontColor"
  | "formatFontName";
  readonly isComposing: boolean;
}
